# Generated by Django 5.0.1 on 2025-11-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
