# Generated by Django 5.2.8 on 2025-11-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0004_passwordhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('comprador', 'Comprador'), ('proveedor', 'Proveedor'), ('logistica', 'Logística'), ('cliente', 'Cliente')], db_index=True, default='cliente', max_length=20),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol', 'estado'], name='usuarios_us_rol_74df2e_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email', 'estado'], name='usuarios_us_email_d0a914_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['-fecha_creacion'], name='usuarios_us_fecha_c_55789a_idx'),
        ),
    ]
