# Generated by Django 5.2.8 on 2025-12-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_options_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('proveedor', 'Proveedor'), ('logistica', 'Logística'), ('cliente', 'Cliente')], db_index=True, default='cliente', max_length=20),
        ),
    ]
