# Generated by Django 5.2.8 on 2025-12-01 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_account_management_fields'),
        ('usuarios', '0006_alter_usuario_rol'),
    ]

    operations = [
    ]
