# Generated by Django 5.0.1 on 2025-11-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='fecha_creacion',
        ),
    ]
