# Generated by Django 5.2.8 on 2025-11-24 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('administrador', models.ForeignKey(help_text='Administrador responsable de la tienda', limit_choices_to={'rol': 'admin'}, on_delete=django.db.models.deletion.PROTECT, related_name='tiendas_administradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('es_basico', models.BooleanField(default=True, help_text='¿Es un producto de necesidad básica?')),
                ('categoria', models.CharField(default='general', help_text='Categoría del producto (por ejemplo: alimentos, bebidas, aseo, dulces, ferretería, etc.)', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(help_text='Proveedor responsable de este producto', limit_choices_to={'rol': 'proveedor'}, on_delete=django.db.models.deletion.PROTECT, related_name='productos_suministrados', to=settings.AUTH_USER_MODEL)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.tienda')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('en_transito', 'En Tránsito'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(help_text='Cliente que realiza el pedido', limit_choices_to={'rol': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='productos.tienda')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='productos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
                'unique_together': {('pedido', 'producto')},
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['tienda', 'activo'], name='productos_p_tienda__bcaf40_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['proveedor', 'activo'], name='productos_p_proveed_8b6597_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('nombre', 'tienda')},
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente', 'estado'], name='productos_p_cliente_25897c_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['tienda', 'estado'], name='productos_p_tienda__a79e11_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado', '-fecha_creacion'], name='productos_p_estado_c1e8fb_idx'),
        ),
    ]
