# Generated by Django 5.0.1 on 2025-11-29 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_caracteristicas_producto_imagen1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_minimo', models.PositiveIntegerField(default=10, help_text='Nivel mínimo de stock que dispara la recarga automática')),
                ('cantidad_recarga', models.PositiveIntegerField(default=50, help_text='Cantidad a agregar cuando se dispara la recarga automática')),
                ('recarga_automatica_activa', models.BooleanField(default=True, help_text='Si está activa, el sistema recargará automáticamente el stock')),
                ('ultima_recarga', models.DateTimeField(blank=True, help_text='Fecha y hora de la última recarga automática', null=True)),
                ('total_recargas', models.PositiveIntegerField(default=0, help_text='Contador de recargas automáticas realizadas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(help_text='Producto al que aplica esta configuración', on_delete=django.db.models.deletion.CASCADE, related_name='config_stock', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Configuración de Stock',
                'verbose_name_plural': 'Configuraciones de Stock',
                'ordering': ['producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialRecarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad agregada al stock')),
                ('stock_anterior', models.PositiveIntegerField(help_text='Stock antes de la recarga')),
                ('stock_nuevo', models.PositiveIntegerField(help_text='Stock después de la recarga')),
                ('tipo', models.CharField(choices=[('automatica', 'Automática'), ('manual', 'Manual')], default='manual', max_length=15)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_recargas', to='productos.producto')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la recarga (null si fue automática)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recargas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Recarga',
                'verbose_name_plural': 'Historial de Recargas',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['producto', '-fecha_creacion'], name='productos_h_product_61a693_idx'), models.Index(fields=['tipo', '-fecha_creacion'], name='productos_h_tipo_ed96ea_idx')],
            },
        ),
    ]
