# Generated by Django 5.0.4 on 2025-12-12 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('productos', '0004_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria_rel',
            field=models.ForeignKey(blank=True, help_text='Referencia a la categoría (Nueva Implementación)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='categorias.categoria'),
        ),
    ]
