# Generated by manual intervention
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_categoria_rel'),
    ]

    operations = [
        # 1. Remove the old char field
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        # 2. Rename the new FK field to 'categoria'
        migrations.RenameField(
            model_name='producto',
            old_name='categoria_rel',
            new_name='categoria',
        ),
    ]
