# Generated by Django 5.2.8 on 2025-12-12 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('productos', '0007_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=6, help_text='Categoría del producto', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='categorias.categoria'),
            preserve_default=False,
        ),
    ]
