# Generated by Django 5.0.4 on 2025-12-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Slug único para URLs de categoría', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve de la categoría', null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen representativa de la categoría', null=True, upload_to='categorias/')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la categoría está activa y visible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
    ]
